### ISSUE TITLE
Initial builds not successful

### ISSUE THREAD

**Issue by ghost** [conda-forge/flake8-quotes-feedstock#1]
After [conda-forge/staged-recipes#1450](https://github.com/conda-forge/staged-recipes/pull/1450) was accepted, there were some problems with the initial builds in this repo.

Looks like the package was built successfully by the appveyor and circle ci jobs, but something went wrong communicating with anaconda.org.

https://circleci.com/gh/conda-forge/flake8-quotes-feedstock/1

```
===== flake8-quotes-0.8.1-py34_0 OK =====
TEST END: flake8-quotes-0.8.1-py34_0
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /feedstock_root/build_artefacts/linux-64/flake8-quotes-0.8.1-py34_0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 106, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 69, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/mixins/channels.py", line 29, in show_channel
    self._check_response(res, [200])
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/__init__.py", line 200, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ('Not Found: Nothing matches the given URI ([GET] https://api.anaconda.org/channels/conda-forge/main -> 404)', 404)
```

https://ci.appveyor.com/project/conda-forge/flake8-quotes-feedstock/build/1.0.1

```
===== flake8-quotes-0.8.1-py27_0 OK =====
TEST END: flake8-quotes-0.8.1-py27_0
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload C:\conda\conda-bld\win-32\flake8-quotes-0.8.1-py27_0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes
python ci_support\upload_or_check_non_existence.py .\recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "ci_support\upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "ci_support\upload_or_check_non_existence.py", line 106, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "ci_support\upload_or_check_non_existence.py", line 69, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "C:\conda\lib\site-packages\binstar_client\mixins\channels.py", line 28, in show_channel
    res = self.session.get(url)
  File "C:\conda\lib\site-packages\requests\sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "C:\conda\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\conda\lib\site-packages\requests\sessions.py", line 608, in send
    r.content
  File "C:\conda\lib\site-packages\requests\models.py", line 737, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\conda\lib\site-packages\requests\models.py", line 663, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Command exited with code 1
```

I'll try re-running the jobs and see if it sorts itself out.

**Comment by ghost** [comment]
Started:
- https://circleci.com/gh/conda-forge/flake8-quotes-feedstock/2
- https://ci.appveyor.com/project/conda-forge/flake8-quotes-feedstock/build/1.0.2

**Comment by ghost** [comment]
Restarting worked for circle ci, but not appveyor, but the appveyor error messages all look like the error message circle ci got initially.

Started:
- https://ci.appveyor.com/project/conda-forge/flake8-quotes-feedstock/build/1.0.3

**Comment by ghost** [comment]
Re-running the jobs was a success!
